.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplos2.09 - Debug ]----------"
	@cd "Ejemplos2.09" && "$(MAKE)" -f  "Ejemplos2.09.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplos2.09 - Debug ]----------"
	@cd "Ejemplos2.09" && "$(MAKE)" -f  "Ejemplos2.09.mk" clean
