.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplos2.12 - Debug ]----------"
	@cd "Ejemplos2.12" && "$(MAKE)" -f  "Ejemplos2.12.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplos2.12 - Debug ]----------"
	@cd "Ejemplos2.12" && "$(MAKE)" -f  "Ejemplos2.12.mk" clean
