.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo5 - Debug ]----------"
	@cd "Ejemplo5" && "$(MAKE)" -f  "Ejemplo5.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo5 - Debug ]----------"
	@cd "Ejemplo5" && "$(MAKE)" -f  "Ejemplo5.mk" clean
