.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo4 - Debug ]----------"
	@cd "Ejemplo4" && "$(MAKE)" -f  "Ejemplo4.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo4 - Debug ]----------"
	@cd "Ejemplo4" && "$(MAKE)" -f  "Ejemplo4.mk" clean
